const students = [{
    "id": 1,
    "first_name": "Janek",
    "last_name": "Caldairou",
    "email": "jcaldairou0@cornell.edu"
  }, {
    "id": 2,
    "first_name": "Jewell",
    "last_name": "Alam",
    "email": "jalam1@nsw.gov.au"
  }, {
    "id": 3,
    "first_name": "Brewster",
    "last_name": "Ostridge",
    "email": "bostridge2@symantec.com"
  }, {
    "id": 4,
    "first_name": "Benjamen",
    "last_name": "Agett",
    "email": "bagett3@gnu.org"
  }, {
    "id": 5,
    "first_name": "Valerie",
    "last_name": "Kildea",
    "email": "vkildea4@vistaprint.com"
  }, {
    "id": 6,
    "first_name": "Konstanze",
    "last_name": "Roebuck",
    "email": "kroebuck5@flavors.me"
  }, {
    "id": 7,
    "first_name": "Kiley",
    "last_name": "Janse",
    "email": "kjanse6@ehow.com"
  }, {
    "id": 8,
    "first_name": "Kasey",
    "last_name": "McGuinley",
    "email": "kmcguinley7@qq.com"
  }, {
    "id": 9,
    "first_name": "Bernete",
    "last_name": "Caseri",
    "email": "bcaseri8@theglobeandmail.com"
  }, {
    "id": 10,
    "first_name": "Christy",
    "last_name": "Godspeede",
    "email": "cgodspeede9@sfgate.com"
}]

module.exports = students